name: Stargate
main: net.TheDgtl.Stargate.Stargate
version: @version@
description: The 1.13 - 1.16 ESR release for Stargate -- Minecraft's original portal plugin.
authors: [Drakia, PseudoKnight, contributors from the SG-Rewritten Project (including Thorin, Pheotis, Ghost, \& Knarvik), and contributors for the LCLO (including Frostalf, InteriorCamping, LittleBigBug, \& TheViperShow)]
softdepend: [Vault]
website: https://sgrewritten.org
api-version: 1.13
commands:
  sg:
    description: Used to reload the plugin. Console use only.
    usage: /<command> reload - Used to reload the plugin. Console use only.
permissions:
  stargate.*:
    children:
      stargate.use:
        description: Allow use of all gates linking to any world in any network
        default: true
      stargate.enter:
        description: Allow entering gates opened by other players
        default: op
      stargate.create:
        description: Allow creating gates on any network
        default: op
      stargate.destroy:
        description: Allow destruction gates on any network
        default: op
      stargate.free:
        description: Allow free use/creation/destruction of gates
        default: op
      stargate.option:
        description: Allow use of all options
        default: op
      stargate.admin:
        description: Allow all admin features (Hidden/Private only so far)
        default: op
